### PR TITLE
Add support for 'other' option in selecting school

### LINKED ISSUE #45: Add an "other" option for school selection
Students who can't find their school can't currently register. We should provide an "other" option in the event that the MLH list does not contain their school.

### PR DESCRIPTION
**Pull request by noahbass**
We've had a number of messages that their school is not listed on the MLH list.

Note: this is to merge into the snyderks-typeahead branch.

Should close #45

### CODE REVIEW

**Comment by kurtlewis** [comment]
I very much appreciate the gif for me. Does this require a backend change?

**Comment by noahbass** [comment]
No backend changes needed for this. When active, the new input is saved to the same name as the typehead input is currently being saved (`school`).

**Comment by kurtlewis** [comment]
Should we be adding another flag to mark their selected school wasn't on the MLH list though?

**Comment by noahbass** [comment]
Ok, good call. We'll send 'schoolOther' to the registration api as a field. Added a PR to the api to support this: https://github.com/RevolutionUC/revolutionuc-website/pull/139.

**Pull request merged**
