### PR TITLE
Changed one small boi to fix video sizing on larger screens

### PR DESCRIPTION
**Pull request by isiah-lloyd**
Fixes the issues seen in the screenshot in #5. Seems to happen on larger screens or weird window sizes.

### CODE REVIEW

**Comment by noahbass** [comment]
This definitely fixes the overlay issue, but brings up a new issue when you load and resize certain widths:

screen shot 2017-12-13 at 3 29 53 pm

screen shot 2017-12-13 at 3 29 33 pm

**Comment by isiah-lloyd** [comment]
I don't see it? Is it the aspect ratio of the video you're talking about?

**Comment by noahbass** [comment]
Yes. The video gets scrunched or stretched when you resize

**Comment by isiah-lloyd** [comment]
After messing around I think we have to choose one or another. I think the video is expanding outside the hero in order to maintain it's aspect ratio which is what `cover` does.

**Comment by noahbass** [comment]
Since it does expand outside of the hero, could we use a low z-index for the video so any expansion is underneath the content below?

**Comment by isiah-lloyd** [comment]
It seemed to be an even simpler fix...just adding a background color to `main` so it covers up the video.

**Comment by noahbass** [comment]
But the video is still being stretched?

**Comment by isiah-lloyd** [comment]
I was dumb and was doing changes in developer tools that I forgot to transfer over. It should work now.

**Pull request merged**
