### PR TITLE
Update FAQ page

### PR DESCRIPTION
**Pull request by noahbass**
- Collapsable sections and section styling
  - Image for page
  - 'expand all' and 'collapse all' helpers
  - Move faq content to `_data/faq.yml` for easier modification in the future

### CODE REVIEW

**Comment by isiah-lloyd** [comment]
I don't think the Polyfill is working correctly, on Edge the questions appear as a bulleted list which isn't bad but if we decide to keep it that way we should hide the `expand/collapse all` buttons.

image

**Comment by isiah-lloyd** [comment]
I just looked at the network tab in Edge and the Polyfill isn't being loaded.

**Comment by noahbass** [comment]
So apparently the if IE tags only catches IE10 and earlier, so I removed that. Now the polyfill always loads on the faq page.

**Comment by isiah-lloyd** [comment]
It works on Edge now but the expand/collapse all just brings you to the top of the page. I get the error 
` SCRIPT5002: SCRIPT5002: Function expected      faq (179,13)` in console.`

**Comment by noahbass** [comment]
I think it was because `event.preventDefault()` doesn't work in IE. I added `event.returnValue = false` to achieve the same effect in IE.

**Comment by isiah-lloyd** [comment]
Still doesn't work, same error. It has a problem with this line
`const details = [...document.getElementsByTagName('details')];`

**Comment by noahbass** [comment]
Ok, I think that should do it

**Pull request merged**
