### PR TITLE
Added turbolinks

### PR DESCRIPTION
**Pull request by snyderks**
[Turbolinks](https://github.com/turbolinks/turbolinks) allows a simulation of a SPA by doing an XHR request when a link is clicked
Replaces the <body> with the returned HTML
Edits history and current location correctly

Fixes:
Added guards around our JS files to check if they've been loaded already
Made the MLH logo persistent since it's on every page and so only needs to be loaded once

### CODE REVIEW

**Comment by domfarolino** [comment]
Curious about the base change and the various older commits? Also are we just looking at merging this to staging to test it out internally? If it is ready to go, I'm comfortable bypassing staging and pushing into master. Will be testing and taking a look at it tonight

**Comment by snyderks** [comment]
The change is for testing internally before merging to master. I'd like to keep in in staging and then backfill everything in master before taking it fully live on the main domain, since it results in some differences in how the other JS runs.

**Comment by snyderks** [comment]
I think the older commits are because the base change pulled in some of the commits made directly to master

**Comment by domfarolino** [comment]
@snyderks did you ever figure out the issue with navigating away from the home page with turbolinks? Also are we going to have to rebase to fix the conflicts or something hmm?

**Comment by snyderks** [comment]
Fixed issues with the home page and made scrolling work on Safari. (also merged master in). Ready for more checks before merging into staging.

**Pull request merged**
