### PR TITLE
Create Rakefile

### PR DESCRIPTION
**Pull request by isiah-lloyd**
I was done typing `bundle exec jekyll serve` all the time so now all you have to do is type `rake`

Tasks are:
* rake - serves the project
* rake serve - same as above
* rake build - builds the project
* rake test - builds and runs tests

### CODE REVIEW

**Comment by noahbass** [comment]
LGTM.

But doesn't show that a server is running when you run the `rake` or `rake serve` task.

**Comment by isiah-lloyd** [comment]
@noahbass Yeah, I noticed it cut a bit of the output out for me too. I'll look into fixing it but I'm going to merge it now.

**Comment by noahbass** [comment]
Idk what changed, but it's behaving as normal for me now @isiah-lloyd 
untitled

**Comment by isiah-lloyd** [comment]
@noahbass I silently pushed to master a fix!

**Pull request merged**
