### PR TITLE
Fix for video playing with turbolinks

### LINKED ISSUE #58: Homepage video stops after coming back from another page
Steps to reproduce:

- Go to the homepage
- Click on a link to another page (like 'Schedule')
- Click on 'Home'

### PR DESCRIPTION
**Pull request by snyderks**
Added a better determination of whether the video is loaded

Added an event listener for when turbolinks loads a page

Fixes #58

### CODE REVIEW

**Comment by noahbass** [comment]
Works better than before, but doesn't work when you do:

- Go to a page other than the homepage (like 'Schedule')
- Refresh
- Click on 'Home'

**Comment by domfarolino** [comment]
Any update on this?

**Comment by snyderks** [comment]
Nothing yet. I haven't been able to get this to work in a reasonable
manner. I'm considering ripping out turbolinks entirely because of it.
Thoughts?

On Tue, Feb 27, 2018 at 10:54 AM, Dominic Farolino <notifications@github.com

**Comment by domfarolino** [comment]
I'm ok with ripping out Turbolinks (at this point, it would be for future iterations of this site of course). I think that's a good-enough idea, also I've had some issues with it and the dashboard I think, it kind of makes it harder (without something like webpack working) to add new things to certain pages as feature additions now come with the prerequisite of adding "clever" little flag-checks to determine if certain things have already been loaded/defined.

----

I think we should rollback all live site commits and remove turbolinks from the site that existed a few days ago and continue from there.

**Pull request closed without merging**
